### PR TITLE
Cljs implementation

### PR DESCRIPTION
**Pull request by nberger**
Tweaks the base implementation by EwenG (https://github.com/EwenG/ring-buffer/commit/49dbf8eada0aa42baba890ef97f09cf99453971c) to make it work.

Make the tests to run in both clj & cljs.

Upgrade to clojure 1.7.0 to use reader conditionals

### CODE REVIEW

**Comment by amalloy** [comment]
I'm happy to merge this, once I am sure I understand what the deal is with cljc files. cljc files are unusable by anyone on 1.6 or below, right? So you can't run the tests on an old version, but since you've included full-length .clj and .cljs files for the actual source, the library will continue to function on older versions of clojure? If so, that's fine with me.

But, please clean up the history so there aren't three different commits saying "cljs implementation". I'm ambivalent as to whether you leave a merge commit in there or rebase onto amalloy/master instead.

**Comment by nberger** [comment]
> I'm happy to merge this, once I am sure I understand what the deal is with cljc files. cljc files are unusable by anyone on 1.6 or below, right?

Right

> So you can't run the tests on an old version, but since you've included full-length .clj and .cljs files for the actual source, the library will continue to function on older versions of clojure? If so, that's fine with me.

In theory yes. But thinking a bit more about it, I'm not sure what role plays the declared 1.7 dependency declared in project.clj. I'd say that it would be ignored in any project that explicitly declares 1.6, but I'll check it better.

> But, please clean up the history so there aren't three different commits saying "cljs implementation". I'm ambivalent as to whether you leave a merge commit in there or rebase onto amalloy/master instead.

Sure. I did it this way because I wanted to keep credit on where the base commit came from. I'll rebase it to the current amalloy/master, and leave two commits: one with the cljs implementation and another with the tests and changes in project.clj

**Comment by nberger** [comment]
Pushed the new commits. Checked on a project using 1.6 and it works just fine. And there's always the option for any user to use the version 1.1.

By the way, I see this commits are being done into 1.1. It might be a good idea to change the version to 1.1-SNAPSHOT, until 1.2 is released. What do you think about that?

Let me know how it looks now, and if I can help with anything else.

**Comment by amalloy** [comment]
I agree in theory with the version numbering, but in practice a lot of projects (including this one) are not particularly careful about that, and have numerous commits whose project.clj all say "1.1" or whatever. So I'll just take this, fix an unrelated bug I noticed, and release 1.2.

**Comment by nberger** [comment]
Sounds good :). Thanks for merging!

**Pull request merged**
